
import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import { ArticlesProvider } from "@/context/articleContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <ArticlesProvider>
       
                <Nav/>
                {children}
          </ArticlesProvider>
      </body>
        
    </html>
  );
}
